[2025-04-23T16:57:35.722+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T16:57:25.840802+00:00 [queued]>
[2025-04-23T16:57:35.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T16:57:25.840802+00:00 [queued]>
[2025-04-23T16:57:35.735+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-23T16:57:35.759+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_data_to_s3_task> on 2025-04-23 16:57:25.840802+00:00
[2025-04-23T16:57:35.768+0000] {standard_task_runner.py:57} INFO - Started process 712 to run task
[2025-04-23T16:57:35.777+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'prayer_times_data_pipeline', 'upload_data_to_s3_task', 'manual__2025-04-23T16:57:25.840802+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/Extract.py', '--cfg-path', '/tmp/tmp_prbs1a0']
[2025-04-23T16:57:35.782+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask upload_data_to_s3_task
[2025-04-23T16:57:35.856+0000] {task_command.py:416} INFO - Running <TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T16:57:25.840802+00:00 [running]> on host d02bd472f10d
[2025-04-23T16:57:36.116+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prayer_times_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T16:57:25.840802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T16:57:25.840802+00:00'
[2025-04-23T16:57:36.124+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-04-23T16:57:36.851+0000] {Extract.py:63} INFO - Upload successful.
[2025-04-23T16:57:36.853+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-23T16:57:36.859+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prayer_times_data_pipeline, task_id=upload_data_to_s3_task, execution_date=20250423T165725, start_date=20250423T165735, end_date=20250423T165736
[2025-04-23T16:57:36.913+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-23T16:57:36.931+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
