[2025-04-23T15:14:32.366+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T15:14:10.964841+00:00 [queued]>
[2025-04-23T15:14:32.372+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T15:14:10.964841+00:00 [queued]>
[2025-04-23T15:14:32.372+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-23T15:14:32.390+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_data_to_s3_task> on 2025-04-23 15:14:10.964841+00:00
[2025-04-23T15:14:32.399+0000] {standard_task_runner.py:57} INFO - Started process 415 to run task
[2025-04-23T15:14:32.402+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'prayer_times_data_pipeline', 'upload_data_to_s3_task', 'manual__2025-04-23T15:14:10.964841+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/Extract.py', '--cfg-path', '/tmp/tmp78g2w2ao']
[2025-04-23T15:14:32.404+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask upload_data_to_s3_task
[2025-04-23T15:14:32.450+0000] {task_command.py:416} INFO - Running <TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T15:14:10.964841+00:00 [running]> on host d02bd472f10d
[2025-04-23T15:14:32.763+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prayer_times_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T15:14:10.964841+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T15:14:10.964841+00:00'
[2025-04-23T15:14:34.133+0000] {logging_mixin.py:151} INFO - Upload successful.
[2025-04-23T15:14:34.135+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-23T15:14:34.143+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prayer_times_data_pipeline, task_id=upload_data_to_s3_task, execution_date=20250423T151410, start_date=20250423T151432, end_date=20250423T151434
[2025-04-23T15:14:34.182+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-23T15:14:34.193+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
