[2025-04-22T17:15:22.396+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-22T16:55:51.418820+00:00 [queued]>
[2025-04-22T17:15:22.403+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-22T16:55:51.418820+00:00 [queued]>
[2025-04-22T17:15:22.405+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-04-22T17:15:22.424+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_data_to_s3_task> on 2025-04-22 16:55:51.418820+00:00
[2025-04-22T17:15:22.443+0000] {standard_task_runner.py:57} INFO - Started process 289 to run task
[2025-04-22T17:15:22.446+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'prayer_times_data_pipeline', 'upload_data_to_s3_task', 'manual__2025-04-22T16:55:51.418820+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/Extract.py', '--cfg-path', '/tmp/tmpxkd27kih']
[2025-04-22T17:15:22.447+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask upload_data_to_s3_task
[2025-04-22T17:15:22.492+0000] {task_command.py:416} INFO - Running <TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-22T16:55:51.418820+00:00 [running]> on host d02bd472f10d
[2025-04-22T17:15:22.791+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prayer_times_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T16:55:51.418820+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T16:55:51.418820+00:00'
[2025-04-22T17:15:23.974+0000] {logging_mixin.py:151} INFO - Upload successful.
[2025-04-22T17:15:23.976+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-22T17:15:23.982+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prayer_times_data_pipeline, task_id=upload_data_to_s3_task, execution_date=20250422T165551, start_date=20250422T171522, end_date=20250422T171523
[2025-04-22T17:15:24.026+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-22T17:15:24.039+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
